const videos = {
    Navasana: "8KsyQvwi85Q",
    "Ardha Navasana": "0495rbXZMQg",
    Marjaryasana: "LGLIyrfTiUc",
    Utkatasana: "4xyTmX_OMiM",
    Bakasana: "2uBjpDLf8bw",
    "Ardha Pincha Mayurasana": "W9qEcTjmA78",
    Phalakasana: "LrqECYmDexQ",
    Vasisthasana: "p1SyVFVtLgk",
    "Baddha Konasana": "-oWWAuKc5Ww",
    Paschimottanasana: "zNbPjCubeQY",
    Padmasana: "w_j4lnfRC38",
    "Ardha Matsyendrasana": "yYy6w8_hLTE",
    Hanumanasana: "xCt5vzGiSlo",
    "Upavistha Konasana": "ZYrXPjPrDSg",
    "Adho Mukha Svanasana": "6Ep5VzGqDRU",
    "Utthita Parsvakonasana": "aoB5L6AxckU",
    "Pincha Mayurasana": "jLhPgyTq7iM",
    "Adho Mukha Vrksasana": "9u6wuuODdZo",
    "Parsva Virabhadrasana": "MoVLJ-NS67E",
    Trikonasana: "NMnmn8Z39Cc",
    "Virabhadrasana One": "0UDKyrhJq-M",
    "Virabhadrasana Two": "s4JqhXZvVpg",
    "Virabhadrasana Three": "uEc5hrgIYx4",
    "Urdhva Dhanurasana": "BrWOyKGoO9g",
    Dhanurasana: "wgH2PdPnZGM",
    Ustrasana: "8q7GxnIFsQo",
    Bitilasana: "W5KVx0ZbB_4",
    "Salamba Bhujangasana": "yvsgUzpMP1M",
    "Urdhva Mukha Svsnssana": "cQtfujS-BhY",
    Camatkarasana: "XNzE5a0hL0U",
    "Setu Bandha Sarvangasana": "g78vfuC4QBI",
    "Supta Kapotasana": "WDOBkhKEuu0",
    "Eka Pada Rajakapotasana": "U2oimBogB4k",
    Uttanasana: "nq8CEGk9a3o",
    Parsvottanasana: "4EllxAKjEMw",
    Garudasana: "9wwtGegsD4E",
    "Utthita Hasta Padangusthasana": "kcRs6Bm4kFo",
    Alanasana: "AgyOiXdOYrw",
    "Ardha Chandrasana": "csErxVR7dpA",
    Anjaneyasana: "FbbcNo-Au1s",
    Malasana: "KTxVYk-Bqv4",
    "Ashta Chandrasana": "EOvDUWykE-s",
    Vrksasana: "Fr5kiIygm0c",
    Halasana: "qpuY0jXimtQ",
    "Salamba Sarvangasana": "g3wvIPXZ-Qo",
    Balasana: "2MJGg-dUKh0",
    Sivasana: "1VYlOKUdylM"
}

export default videos;